name: Develop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Install dependencies
      - run: npm ci

      # Run linter
      - run: npm run lint

      # Run tests
      - run: npm run test
